### ISSUE TITLE
Test failure on windows

### ISSUE THREAD

**Issue by relf** [rust-ml/linfa-linalg#12]
Running tests on Windows (`stable-windows-msvc`), I get the following error:

```bash
>cargo test --doc
    Finished test [unoptimized + debuginfo] target(s) in 0.13s
   Doc-tests linfa-linalg

running 4 tests
test src\lobpcg\svd.rs - lobpcg::svd::TruncatedSvd<A,R>::decompose (line 163) ... FAILED
test src\lobpcg\eig.rs - lobpcg::eig::TruncatedEigIterator (line 201) ... ok
test src\lobpcg\eig.rs - lobpcg::eig::TruncatedEig<A,R>::decompose (line 123) ... ok
test src\lobpcg\eig.rs - lobpcg::eig::TruncatedEig (line 25) ... ok

failures:

---- src\lobpcg\svd.rs - lobpcg::svd::TruncatedSvd<A,R>::decompose (line 163) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', D:\rlafage\workspace\linfa-linalg\src\eigh.rs:310:78
stack backtrace:
   0:     0x7ff786fe0e31 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff786fe0e31 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff786fe0e31 - std::sys_common::backtrace::_print_fmt
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff786fe0e31 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff786ff4e9a - core::fmt::write
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\fmt\mod.rs:1190
   5:     0x7ff786fde199 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\io\mod.rs:1657
   6:     0x7ff786fe2e32 - std::sys_common::backtrace::_print
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff786fe2e32 - std::sys_common::backtrace::print
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff786fe2e32 - std::panicking::default_hook::closure$1
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:295
   9:     0x7ff786fe29f5 - std::panicking::default_hook
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:314
  10:     0x7ff786fe3488 - std::panicking::rust_panic_with_hook
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:698
  11:     0x7ff786fe3302 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:586
  12:     0x7ff786fe1767 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff786fe2fb9 - std::panicking::begin_panic_handler
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:584
  14:     0x7ff786ffbd15 - core::panicking::panic_fmt
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\panicking.rs:143
  15:     0x7ff786ffbbbc - core::panicking::panic
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\panicking.rs:48
  16:     0x7ff786f6def7 - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  17:     0x7ff786ee8a38 - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  18:     0x7ff786f527b0 - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  19:     0x7ff786f52f31 - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  20:     0x7ff786f53d4f - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  21:     0x7ff786f52763 - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  22:     0x7ff786ee86c5 - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  23:     0x7ff786eea593 - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  24:     0x7ff786ef4f37 - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  25:     0x7ff786f716d8 - std::rt::lang_start::h6e22933c412e8886
  26:     0x7ff786ef0e27 - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  27:     0x7ff786ef7fdf - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  28:     0x7ff786ee1e57 - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  29:     0x7ff786ee1ce9 - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  30:     0x7ff786ee1216 - impl$<ref$<rand_core::block::BlockRng<rand_chacha::chacha::ChaCha8Core> >, core::fmt::Debug>::vtable$
  31:     0x7ff786f6ff77 - std::rt::lang_start::h6e22933c412e8886
  32:     0x7ff786f6ff3c - std::rt::lang_start::h6e22933c412e8886
  33:     0x7ff786fe069f - core::ops::function::impls::impl$2::call_once
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\ops\function.rs:259
  34:     0x7ff786fe069f - std::panicking::try::do_call
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:492
  35:     0x7ff786fe069f - std::panicking::try
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:456
  36:     0x7ff786fe069f - std::panic::catch_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panic.rs:137
  37:     0x7ff786fe069f - std::rt::lang_start_internal::closure$2
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\rt.rs:128
  38:     0x7ff786fe069f - std::panicking::try::do_call
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:492
  39:     0x7ff786fe069f - std::panicking::try
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:456
  40:     0x7ff786fe069f - std::panic::catch_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panic.rs:137
  41:     0x7ff786fe069f - std::rt::lang_start_internal
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\rt.rs:128
  42:     0x7ff786f6ff20 - std::rt::lang_start::h6e22933c412e8886
  43:     0x7ff786f78ec6 - main
  44:     0x7ff786ffa179 - invoke_main
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  45:     0x7ff786ffa179 - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  46:     0x7ff947317c24 - BaseThreadInitThunk
  47:     0x7ff9475ad721 - RtlUserThreadStart



failures:
    src\lobpcg\svd.rs - lobpcg::svd::TruncatedSvd<A,R>::decompose (line 163)

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.42s

error: test failed, to rerun pass '--doc'
```

**Comment by relf** [comment]
As mentioned [here](https://github.com/rust-ml/linfa-linalg/blob/82837ffe0e83ae86866ade019c63772a3bbff979/src/eigh.rs#L308), I get a vector of NaN values which triggers the panic.

**Comment by YuhanLiin** [comment]
Do you also get issues with the non-doc tests? We use seeded RNGs for randomness, so I don't see why the code would run any differently between Linux and Windows, but I'm not the one who wrote LOBPCG so I'm not certain. Can you provide your Rust version and confirm that you're running on the latest main?

I'm considering omitting the LOBPCG module for the first release, since it still has outstanding issues.

**Comment by YuhanLiin** [comment]
Also are you on a 32 or 64 bit system?

**Comment by relf** [comment]
No problem with non doc tests. I use Rust 1.60 and I am on latest main (I've cloned the repo today). 

I've traced the residuals in `lobpcg`, it reaches a minimum in 2 iterations with some L2 norms at ~ `5e-10` but then it diverges till I get NaNs. The algo terminates successfully if L2-norm of residuals is less than `precision*precision`, so I can make it work if I set `precision` to `1e-4` for instance (for which I get `eigvals: [25.00000000390971, 16.00000000063256, 9.000000000107537]`).

**Comment by relf** [comment]
> Also are you on a 32 or 64 bit system?
64 bits

**Comment by YuhanLiin** [comment]
I changed the precision and pushed. Try it now.

**Comment by relf** [comment]
Yep, it works!
